### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by rchekaluk** [NagiosEnterprises/check_mssql_collection#1]
Receive the following error on Ubuntu 14.04, Python 2.7.6:

```
$ /tmp/check_mssql_server.py -H $host -U $dbuser -P $dbpswd --lazywrites -w 20 -c 30
Traceback (most recent call last):
  File "/tmp/check_mssql_server.py", line 464, in <module>
    main()
  File "/tmp/check_mssql_server.py", line 430, in main
    execute_query(mssql, options, host)
  File "/tmp/check_mssql_server.py", line 443, in execute_query
    mssql_query.do(mssql)
  File "/tmp/check_mssql_server.py", line 282, in do
    self.run_on_connection(connection)
  File "/tmp/check_mssql_server.py", line 269, in run_on_connection
    self.query_result = cur.fetchone()[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

However, time2connect works fine using the same credentials:

```
$ /tmp/check_mssql_server.py -H $host -U $dbuser -P $dbpswd --time2connect
OK: Time to connect was 0.0266668796539s|time=0.0266668796539s;;;;;
```

sucustrupador has also report the same error [here](http://exchange.nagios.org/directory/Reviews/sucustrupador/1#/) and [here](http://exchange.nagios.org/directory/Addons/Configuration/Configuration-Wizards/MSSQL-Server-Wizard/details).

**Comment by jsuzack** [comment]
I'm experiencing the same issue on Ubuntu Trusty. Followed the instructions above to no avail. The SQL query returns data in SQL Server Management Studio but not with the Py script. The data returned is NoneType. I swapped the cursor fetchone() call to fetchall(), and it returns an empty list.
