### ISSUE TITLE
check_mssql_server.py has one too many ; in the perfdata string

### ISSUE THREAD

**Issue by box293** [NagiosEnterprises/check_mssql_collection#4]
Using the check_mssql_server.py script there is one too many ; at the end of the performance data string, this causes problems with certain packages that process the performance data.

Here's the fix:
On line 246 remove the last ; so the line is as follows:
```
stdout = '%s%s|%s=%s%s;%s;%s;;' % (prefix, stdout, label, strresult, unit, options.warning or '', options.critical or '')
```

**Comment by scottwilkerson** [comment]
Fixed in both plugins.  Thanks
